-- Run once with a role that can create a database, warehouse, and account role.
-- This package uses isolated object names and does not modify existing databases.

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS PBI_LINEAGE_DEMO_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Isolated warehouse for the ten-level Power BI lineage demo';

CREATE DATABASE IF NOT EXISTS PBI_LINEAGE_DEMO
    COMMENT = 'Synthetic Snowflake-to-Power BI lineage demonstration';

CREATE SCHEMA IF NOT EXISTS PBI_LINEAGE_DEMO.RAW
    COMMENT = 'CSV landing objects';
CREATE SCHEMA IF NOT EXISTS PBI_LINEAGE_DEMO.STAGE
    COMMENT = 'Validation and standardization objects';
CREATE SCHEMA IF NOT EXISTS PBI_LINEAGE_DEMO.CORE
    COMMENT = 'Enrichment and financial logic';
CREATE SCHEMA IF NOT EXISTS PBI_LINEAGE_DEMO.ANALYTICS
    COMMENT = 'Behavior and target analysis';
CREATE SCHEMA IF NOT EXISTS PBI_LINEAGE_DEMO.MART
    COMMENT = 'Power BI presentation objects';

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS PBI_LINEAGE_DEMO_ROLE
    COMMENT = 'Read-only Power BI and lineage-demo role';

GRANT ROLE PBI_LINEAGE_DEMO_ROLE TO ROLE SYSADMIN;

USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE PBI_LINEAGE_DEMO_WH TO ROLE PBI_LINEAGE_DEMO_ROLE;
GRANT USAGE ON DATABASE PBI_LINEAGE_DEMO TO ROLE PBI_LINEAGE_DEMO_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE PBI_LINEAGE_DEMO TO ROLE PBI_LINEAGE_DEMO_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE PBI_LINEAGE_DEMO TO ROLE PBI_LINEAGE_DEMO_ROLE;

USE ROLE ACCOUNTADMIN;

GRANT VIEW LINEAGE ON ACCOUNT TO ROLE PBI_LINEAGE_DEMO_ROLE;

-- Assign the role to the demo user after replacing the placeholder:
-- GRANT ROLE PBI_LINEAGE_DEMO_ROLE TO USER <YOUR_SNOWFLAKE_USER>;

USE ROLE SYSADMIN;
USE WAREHOUSE PBI_LINEAGE_DEMO_WH;
USE DATABASE PBI_LINEAGE_DEMO;
USE SCHEMA RAW;

SELECT
    CURRENT_DATABASE() AS DEMO_DATABASE,
    CURRENT_WAREHOUSE() AS DEMO_WAREHOUSE,
    CURRENT_ROLE() AS BUILD_ROLE;
