USE ROLE SYSADMIN;
USE WAREHOUSE PBI_LINEAGE_DEMO_WH;
USE DATABASE PBI_LINEAGE_DEMO;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT DEMO_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null')
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    COMMENT = 'CSV format for synthetic lineage-demo source files';

CREATE STAGE IF NOT EXISTS DEMO_FILES
    FILE_FORMAT = DEMO_CSV_FORMAT
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Internal stage for the four synthetic demo files';

CREATE OR REPLACE TABLE RAW_ORDER_LINES (
    ORDER_LINE_ID VARCHAR,
    ORDER_ID VARCHAR,
    ORDER_DATE VARCHAR,
    CUSTOMER_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    QUANTITY VARCHAR,
    UNIT_PRICE VARCHAR,
    DISCOUNT_PCT VARCHAR,
    SALES_CHANNEL VARCHAR,
    PAYMENT_MODE VARCHAR,
    ORDER_STATUS VARCHAR,
    SOURCE_FILE VARCHAR,
    INGESTED_AT TIMESTAMP_LTZ
)
COMMENT = 'Level 1: raw order-line records loaded from order_lines.csv';

CREATE OR REPLACE TABLE RAW_CUSTOMERS (
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    SEGMENT VARCHAR,
    REGION VARCHAR,
    JOIN_DATE VARCHAR,
    SOURCE_FILE VARCHAR,
    INGESTED_AT TIMESTAMP_LTZ
)
COMMENT = 'Raw customer branch used to enrich the primary order lineage';

CREATE OR REPLACE TABLE RAW_PRODUCTS (
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    SUB_CATEGORY VARCHAR,
    UNIT_COST VARCHAR,
    LIST_PRICE VARCHAR,
    SOURCE_FILE VARCHAR,
    INGESTED_AT TIMESTAMP_LTZ
)
COMMENT = 'Raw product branch used to enrich the primary order lineage';

CREATE OR REPLACE TABLE RAW_MONTHLY_TARGETS (
    MONTH_START VARCHAR,
    REGION VARCHAR,
    REVENUE_TARGET VARCHAR,
    MARGIN_TARGET_PCT VARCHAR,
    SOURCE_FILE VARCHAR,
    INGESTED_AT TIMESTAMP_LTZ
)
COMMENT = 'Raw monthly target branch used at lineage level 8';

SHOW STAGES LIKE 'DEMO_FILES' IN SCHEMA PBI_LINEAGE_DEMO.RAW;

-- Upload all four files from ../data to @PBI_LINEAGE_DEMO.RAW.DEMO_FILES.
-- Snowsight: Data > Add Data > Load files into a Stage.
-- SnowSQL example:
-- PUT file://C:/absolute/path/order_lines.csv
--     @PBI_LINEAGE_DEMO.RAW.DEMO_FILES AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
