-- Prerequisite: upload order_lines.csv, customers.csv, products.csv, and
-- monthly_targets.csv to @PBI_LINEAGE_DEMO.RAW.DEMO_FILES.

USE ROLE SYSADMIN;
USE WAREHOUSE PBI_LINEAGE_DEMO_WH;
USE DATABASE PBI_LINEAGE_DEMO;
USE SCHEMA RAW;

LIST @DEMO_FILES;

TRUNCATE TABLE RAW_ORDER_LINES;
TRUNCATE TABLE RAW_CUSTOMERS;
TRUNCATE TABLE RAW_PRODUCTS;
TRUNCATE TABLE RAW_MONTHLY_TARGETS;

COPY INTO RAW_ORDER_LINES
FROM (
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
        METADATA$FILENAME,
        CURRENT_TIMESTAMP()
    FROM @DEMO_FILES/order_lines.csv (FILE_FORMAT => DEMO_CSV_FORMAT)
)
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

COPY INTO RAW_CUSTOMERS
FROM (
    SELECT
        $1, $2, $3, $4, $5,
        METADATA$FILENAME,
        CURRENT_TIMESTAMP()
    FROM @DEMO_FILES/customers.csv (FILE_FORMAT => DEMO_CSV_FORMAT)
)
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

COPY INTO RAW_PRODUCTS
FROM (
    SELECT
        $1, $2, $3, $4, $5, $6,
        METADATA$FILENAME,
        CURRENT_TIMESTAMP()
    FROM @DEMO_FILES/products.csv (FILE_FORMAT => DEMO_CSV_FORMAT)
)
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

COPY INTO RAW_MONTHLY_TARGETS
FROM (
    SELECT
        $1, $2, $3, $4,
        METADATA$FILENAME,
        CURRENT_TIMESTAMP()
    FROM @DEMO_FILES/monthly_targets.csv (FILE_FORMAT => DEMO_CSV_FORMAT)
)
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

SELECT 'RAW_ORDER_LINES' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM RAW_ORDER_LINES
UNION ALL
SELECT 'RAW_CUSTOMERS', COUNT(*) FROM RAW_CUSTOMERS
UNION ALL
SELECT 'RAW_PRODUCTS', COUNT(*) FROM RAW_PRODUCTS
UNION ALL
SELECT 'RAW_MONTHLY_TARGETS', COUNT(*) FROM RAW_MONTHLY_TARGETS
ORDER BY OBJECT_NAME;
