USE ROLE SYSADMIN;
USE WAREHOUSE PBI_LINEAGE_DEMO_WH;
USE DATABASE PBI_LINEAGE_DEMO;

ALTER TABLE MART.FACT_PBI_SALES_STORY MODIFY COLUMN ORDER_LINE_ID
    COMMENT 'Unique grain of the Power BI fact table';
ALTER TABLE MART.FACT_PBI_SALES_STORY MODIFY COLUMN NET_SALES
    COMMENT 'Signed revenue after discount; returned lines are negative';
ALTER TABLE MART.FACT_PBI_SALES_STORY MODIFY COLUMN GROSS_PROFIT
    COMMENT 'Signed net sales less signed product cost';
ALTER TABLE MART.FACT_PBI_SALES_STORY MODIFY COLUMN REVENUE_TARGET_ALLOCATED
    COMMENT 'Regional monthly target allocated across fact rows for additive Power BI measures';
ALTER TABLE MART.FACT_PBI_SALES_STORY MODIFY COLUMN STORY_SIGNAL
    COMMENT 'Explainable business label for growth, margin pressure, or return leakage';
ALTER TABLE MART.FACT_PBI_SALES_STORY MODIFY COLUMN SOURCE_FILE
    COMMENT 'Original staged CSV file captured during ingestion';

GRANT SELECT ON ALL TABLES IN DATABASE PBI_LINEAGE_DEMO
    TO ROLE PBI_LINEAGE_DEMO_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE PBI_LINEAGE_DEMO
    TO ROLE PBI_LINEAGE_DEMO_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE PBI_LINEAGE_DEMO
    TO ROLE PBI_LINEAGE_DEMO_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE PBI_LINEAGE_DEMO
    TO ROLE PBI_LINEAGE_DEMO_ROLE;

SHOW GRANTS TO ROLE PBI_LINEAGE_DEMO_ROLE;
