USE ROLE SYSADMIN;
USE WAREHOUSE PBI_LINEAGE_DEMO_WH;
USE DATABASE PBI_LINEAGE_DEMO;

-- 1. Confirm the physical objects and their table/view types.
SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    COMMENT
FROM PBI_LINEAGE_DEMO.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('RAW', 'STAGE', 'CORE', 'ANALYTICS', 'MART')
ORDER BY TABLE_SCHEMA, TABLE_NAME;

-- 2. Confirm row movement through each primary level.
SELECT 1 AS LINEAGE_LEVEL, 'RAW.RAW_ORDER_LINES' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT
FROM RAW.RAW_ORDER_LINES
UNION ALL
SELECT 2, 'STAGE.V_ORDER_VALIDATED', COUNT(*) FROM STAGE.V_ORDER_VALIDATED
UNION ALL
SELECT 3, 'STAGE.T_ORDER_VALIDATED', COUNT(*) FROM STAGE.T_ORDER_VALIDATED
UNION ALL
SELECT 4, 'CORE.V_ORDER_ENRICHED', COUNT(*) FROM CORE.V_ORDER_ENRICHED
UNION ALL
SELECT 5, 'CORE.T_ORDER_FINANCIALS', COUNT(*) FROM CORE.T_ORDER_FINANCIALS
UNION ALL
SELECT 6, 'CORE.V_ORDER_BEHAVIOR', COUNT(*) FROM CORE.V_ORDER_BEHAVIOR
UNION ALL
SELECT 7, 'ANALYTICS.T_ORDER_BEHAVIOR', COUNT(*) FROM ANALYTICS.T_ORDER_BEHAVIOR
UNION ALL
SELECT 8, 'ANALYTICS.V_SALES_TARGET_STATUS', COUNT(*) FROM ANALYTICS.V_SALES_TARGET_STATUS
UNION ALL
SELECT 9, 'MART.T_SALES_STORY', COUNT(*) FROM MART.T_SALES_STORY
UNION ALL
SELECT 10, 'MART.FACT_PBI_SALES_STORY', COUNT(*) FROM MART.FACT_PBI_SALES_STORY
ORDER BY LINEAGE_LEVEL;

-- 3. Explain which source rows were intentionally removed.
SELECT
    DATA_QUALITY_STATUS,
    ORDER_STATUS,
    COUNT(*) AS ROW_COUNT
FROM STAGE.V_ORDER_VALIDATED
GROUP BY DATA_QUALITY_STATUS, ORDER_STATUS
ORDER BY DATA_QUALITY_STATUS, ORDER_STATUS;

-- 4. Validate the KPIs that will appear in Power BI.
SELECT
    ROUND(SUM(NET_SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(GROSS_PROFIT), 2) AS GROSS_PROFIT,
    ROUND(SUM(GROSS_PROFIT) / NULLIF(SUM(NET_SALES), 0), 4) AS GROSS_MARGIN_PCT,
    COUNT(DISTINCT ORDER_ID) AS DISTINCT_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID) AS DISTINCT_CUSTOMERS,
    ROUND(SUM(REVENUE_TARGET_ALLOCATED), 2) AS REVENUE_TARGET,
    ROUND(
        SUM(NET_SALES) / NULLIF(SUM(REVENUE_TARGET_ALLOCATED), 0),
        4
    ) AS TARGET_ATTAINMENT_PCT
FROM MART.FACT_PBI_SALES_STORY;

-- 5. Validate the intended recovery story.
SELECT
    CASE
        WHEN MONTH(MONTH_START) <= 4 THEN 'Jan-Apr'
        WHEN MONTH(MONTH_START) <= 8 THEN 'May-Aug'
        ELSE 'Sep-Dec'
    END AS STORY_PERIOD,
    ROUND(SUM(NET_SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(REVENUE_TARGET_ALLOCATED), 2) AS REVENUE_TARGET,
    ROUND(
        SUM(NET_SALES) / NULLIF(SUM(REVENUE_TARGET_ALLOCATED), 0),
        4
    ) AS TARGET_ATTAINMENT_PCT
FROM MART.FACT_PBI_SALES_STORY
GROUP BY STORY_PERIOD
ORDER BY MIN(MONTH(MONTH_START));

-- 6. Snowflake GET_LINEAGE returns at most five levels per call.
-- This first segment covers final Level 10 back to Level 5.
SELECT *
FROM TABLE(
    SNOWFLAKE.CORE.GET_LINEAGE(
        'PBI_LINEAGE_DEMO.MART.FACT_PBI_SALES_STORY',
        'TABLE',
        'UPSTREAM',
        5
    )
)
ORDER BY DISTANCE;

-- 7. This second segment covers Level 5 back to the raw branches.
SELECT *
FROM TABLE(
    SNOWFLAKE.CORE.GET_LINEAGE(
        'PBI_LINEAGE_DEMO.CORE.T_ORDER_FINANCIALS',
        'TABLE',
        'UPSTREAM',
        5
    )
)
ORDER BY DISTANCE;

-- 8. Demonstrate downstream impact from the raw order table.
SELECT *
FROM TABLE(
    SNOWFLAKE.CORE.GET_LINEAGE(
        'PBI_LINEAGE_DEMO.RAW.RAW_ORDER_LINES',
        'TABLE',
        'DOWNSTREAM',
        5
    )
)
ORDER BY DISTANCE;

-- 9. Demonstrate column lineage for the final revenue field.
SELECT *
FROM TABLE(
    SNOWFLAKE.CORE.GET_LINEAGE(
        'PBI_LINEAGE_DEMO.MART.FACT_PBI_SALES_STORY.NET_SALES',
        'COLUMN',
        'UPSTREAM',
        5
    )
)
ORDER BY DISTANCE;
