USE ROLE PBI_LINEAGE_DEMO_ROLE;
USE WAREHOUSE PBI_LINEAGE_DEMO_WH;
USE DATABASE PBI_LINEAGE_DEMO;
USE SCHEMA MART;

-- Query A: monthly actual versus target, matching the main Power BI chart.
SELECT
    MONTH_START,
    ROUND(SUM(NET_SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(REVENUE_TARGET_ALLOCATED), 2) AS REVENUE_TARGET,
    ROUND(
        SUM(NET_SALES) / NULLIF(SUM(REVENUE_TARGET_ALLOCATED), 0),
        4
    ) AS TARGET_ATTAINMENT_PCT
FROM FACT_PBI_SALES_STORY
GROUP BY MONTH_START
ORDER BY MONTH_START;

-- Query B: identify the regions driving the annual result.
SELECT
    REGION,
    ROUND(SUM(NET_SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(GROSS_PROFIT), 2) AS GROSS_PROFIT,
    ROUND(SUM(GROSS_PROFIT) / NULLIF(SUM(NET_SALES), 0), 4) AS GROSS_MARGIN_PCT,
    ROUND(SUM(REVENUE_TARGET_ALLOCATED), 2) AS REVENUE_TARGET
FROM FACT_PBI_SALES_STORY
GROUP BY REGION
ORDER BY TOTAL_REVENUE DESC;

-- Query C: identify category and segment combinations that explain performance.
SELECT
    CATEGORY,
    CUSTOMER_SEGMENT,
    ROUND(SUM(NET_SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(GROSS_PROFIT), 2) AS GROSS_PROFIT,
    COUNT(DISTINCT ORDER_ID) AS ORDERS
FROM FACT_PBI_SALES_STORY
GROUP BY CATEGORY, CUSTOMER_SEGMENT
ORDER BY TOTAL_REVENUE DESC;

-- Query D: quantify revenue leakage from returned orders.
SELECT
    CATEGORY,
    COUNT(DISTINCT IFF(IS_RETURNED = 1, ORDER_ID, NULL)) AS RETURNED_ORDERS,
    ROUND(SUM(IFF(IS_RETURNED = 1, NET_SALES, 0)), 2) AS RETURNED_REVENUE,
    ROUND(SUM(NET_SALES), 2) AS NET_REVENUE
FROM FACT_PBI_SALES_STORY
GROUP BY CATEGORY
ORDER BY RETURNED_REVENUE;

-- Query E: show the explainable story labels used for presenter drill-down.
SELECT
    STORY_SIGNAL,
    COUNT(*) AS ORDER_LINES,
    ROUND(SUM(NET_SALES), 2) AS TOTAL_REVENUE,
    ROUND(SUM(GROSS_PROFIT), 2) AS GROSS_PROFIT
FROM FACT_PBI_SALES_STORY
GROUP BY STORY_SIGNAL
ORDER BY TOTAL_REVENUE DESC;
