-- DESTRUCTIVE: run only when the isolated demo environment is no longer needed.

USE ROLE SYSADMIN;

DROP DATABASE IF EXISTS PBI_LINEAGE_DEMO;
DROP WAREHOUSE IF EXISTS PBI_LINEAGE_DEMO_WH;

USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS PBI_LINEAGE_DEMO_ROLE;
